# Generated by Django 2.2.11 on 2020-03-16 20:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200313_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='author',
            field=models.ForeignKey(blank=True, help_text='автор', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='название'),
        ),
    ]
